==== dbm-status

===== Purpose

Outputs count or list of unrun change sets to STDOUT or a file.

===== Description

Usage:
[source,java]
----
grails <<environment>> dbm-status <<filename>> --verbose=<<verbose>> --contexts=<<contexts>> --defaultSchema=<<defaultSchema>> --dataSource=<<dataSource>>
----

Required arguments: _none_ .

Optional arguments:

* `filename` - The path to the output file to write to. If not specified output is written to the console
* `verbose` - If `true` (the default) the changesets are listed; if `false` only the count is displayed
* `contexts` - A comma-delimited list of http://www.liquibase.org/manual/contexts[context] names. If specified, only changesets tagged with one of the context names will be included
* `defaultSchema` - The default schema name to use
* `dataSource` - if provided will run the script for the specified dataSource.  Not needed for the default dataSource.

NOTE: Note that the `verbose`, `contexts`, `defaultSchema` and `dataSource` parameter name and value must be quoted if executed in Windows, e.g.
[source,groovy]
----
grails dbm-status "--verbose=<<verbose>>" "--contexts=<<contexts>>" "--defaultSchema=<<defaultSchema>>" "--dataSource=<<dataSource>>"
----

NOTE: For the `dataSource` parameter if the data source is configured as `dataSource_reports` in DataSource.groovy
the suffix of `reports` will be used as the parameter value.
[source,groovy]
----
--dataSource=reports
----