==== dbm-mark-next-changeset-ran

===== Purpose

Mark the next change set as executed in the database.

===== Description

If a filename is specified, writes the SQL that will perform the update that file but doesn't update.

Usage:
[source,java]
----
grails <<environment>> dbm-mark-next-changeset-ran <<filename>> --contexts=<<contexts>> --defaultSchema=<<defaultSchema>> --dataSource=<<dataSource>>
----

Required arguments: _none_ .

Optional arguments:

* `filename` - The path to the output file to write to
* `contexts` - A comma-delimited list of http://www.liquibase.org/manual/contexts[context] names. If specified, only changesets tagged with one of the context names will be run
* `defaultSchema` - The default schema name to use
* `dataSource` - if provided will run the script for the specified dataSource.  Not needed for the default dataSource.

NOTE: Note that the `contexts`, `defaultSchema`, and `dataSource` parameter name and value must be quoted if executed in Windows, e.g.
[source,groovy]
----
grails dbm-mark-next-changeset-ran "--contexts=<<contexts>>" "--defaultSchema=<<defaultSchema>>" "--dataSource=<<dataSource>>"
----

NOTE: For the `dataSource` parameter if the data source is configured as `dataSource_reports` in DataSource.groovy
the suffix of `reports` will be used as the parameter value.
[source,groovy]
----
--dataSource=reports
----