== Getting Started

*The first step is to add a dependency for the plugin in `BuildConfig.groovy`:*

[source,groovy,subs="attributes"]
----
plugins {
   ...
   runtime "{groupId}:{artifactId}:{version}"
}
----

*Typical initial workflow*

Next you'll need to create an initial changelog. You can use Liquibase XML or the plugin's Groovy DSL for individual files. You can even mix and match; Groovy files can include other Groovy files and Liquibase XML files (but XML files can't include Groovy files).

Depending on the state of your database and code, you have two options; either create a changelog from the database or create it from your domain classes. The decision tends to be based on whether you prefer to design the database and adjust the domain classes to work with it, or to design your domain classes and use Hibernate to create the corresponding database structure.

To create a changelog from the database, use the <<ref-rollback-scripts-dbm-generate-changelog,dbm-generate-changelog>> script:
[source,groovy]
----
grails dbm-generate-changelog changelog.groovy
----

or

[source,groovy]
----
grails dbm-generate-changelog changelog.xml
----

depending on whether you prefer the Groovy DSL or XML. The filename is relative to the changelog base folder, which defaults to `grails-app/migrations`.

NOTE: If you use the XML format (or use a non-default Groovy filename), be sure to change the name of the file in `Config.groovy` so `dbm-update` and other scripts find the file:
[source,groovy]
----
grails.plugin.databasemigration.changelogFileName = 'changelog.xml'
----

Since the database is already correct, run the <<ref-maintenance-scripts-dbm-changelog-sync,dbm-changelog-sync>> script to record that the changes have already been applied:
[source,groovy]
----
grails dbm-changelog-sync
----

Running this script is primarily a no-op except that it records the execution(s) in the Liquibase DATABASECHANGELOG table.

To create a changelog from your domain classes, use the <<ref-rollback-scripts-dbm-generate-gorm-changelog,dbm-generate-gorm-changelog>> script:

[source,groovy]
----
grails dbm-generate-gorm-changelog changelog.groovy
----

or

[source,groovy]
----
grails dbm-generate-gorm-changelog changelog.xml
----

If you haven't created the database yet, run the <<ref-update-scripts-dbm-update,dbm-update>> script to create the corresponding tables:

[source,groovy]
----
grails dbm-update
----

or the <<ref-maintenance-scripts-dbm-changelog-sync,dbm-changelog-sync>> script if the database is already in sync with your code:

[source,groovy]
----
grails dbm-changelog-sync
----

NOTE: If you use the searchable plugin you need to configure it to run after the database migrations have run. Either in `Searchable.groovy` or in `Config.groovy` (if that's where you configure Searchable):
[source,groovy]
----
// disable the plugin's operations here.  we'll re-enable them in the Bootstrap to avoid conflicts with database-migration
mirrorChanges = false
bulkIndexOnStartup = false
----

[source,groovy]
.Bootstrap.groovy
----
class BootStrap {

   def searchableService

   def init = { servletContext ->
      // do any data loading you would normally do

      // Manually start the mirroring process to ensure that it comes after the automated migrations.
      println "Performing bulk index"
      searchableService.reindex()
      println "Starting mirror service"
      searchableService.startMirroring()
   }
}
----

*Source control*

Now you can commit the changelog and the corresponding application code to source control. Other developers can then update and synchronize their databases, and start doing migrations themselves.

[[autobase]]
include::gettingStarted/autobase.adoc[]