//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.11.21 at 02:46:24 PM EST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.liquibase.org/xml/ns/dbchangelog", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.liquibase.xml.ns.dbchangelog;
